import { ProfileSidebar } from "@/component/sidebar/profileSidbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin-Bark-Buddies",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex relative">
      <ProfileSidebar></ProfileSidebar>
      <div className="mx-auto container">{children}</div>
    </div>
  );
}
